// React/src/orig_App.js
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';
import React, { useEffect, useMemo, useState } from 'react';
import './App.css';
import PivotGrid, { FieldChooser} from 'devextreme-react/pivot-grid'
import CheckBox from 'devextreme-react/check-box'
import service from './service'

let tempSales = service.getSales();
      
tempSales.forEach((sale, index) => {
  sale.isApproved = index % 2 !== 0;
});

const sales = tempSales;
const pivotGridRef = React.createRef();

function App() {
  const [isConditional, setIsConditional] = useState(true)
  
  const dataSource = useMemo(() => { 
    return {
      fields: [{
        caption: 'Region',
        width: 120,
        dataField: 'region',
        area: 'row',
        expanded: true
      }, {
        caption: 'City',
        dataField: 'city',
        width: 150,
        area: 'row',
        selector: citySelector
      }, {
        dataField: 'date',
        dataType: 'date',
        area: 'column',
        expanded: true
      }, {
        caption: 'Sales',
        dataType: 'number',
        summaryType: 'custom',
        format: 'currency',
        area: 'data',
        calculateCustomSummary: calculateCustomSummary
      },{
        caption: "Approved",
        dataField: "isApproved",
        summaryType: "sum",
        area: "data"
      }],
      store: sales
    }
  }, [isConditional])
    
  function calculateCustomSummary(options) {
    switch (options.summaryProcess) {
        case "start":
            options.totalValue = { conditionalVal: 0, rawVal: 0, count: 0 };
            break;
        case "calculate":
            options.totalValue.count += 1;
            options.totalValue.rawVal += options.value.amount;
            if (options.value.isApproved) {
                options.totalValue.conditionalVal += options.value.amount;
            }
            break;
        case "finalize":
            if (options.totalValue.count === 1 || !isConditional) {
                // If not conditional, this block will always be run
                options.totalValue = options.totalValue.rawVal;
            } else {
                options.totalValue = options.totalValue.conditionalVal;
            }
    }
  }

  function onValueChanged({value}) {
    setIsConditional(value)
  }

  return (
    <div className="App">
      <div className="long-title"><h3>Sales Amount by Region</h3></div>
      <PivotGrid id="sales"
        ref={pivotGridRef}
        allowSortingBySummary={true}
        allowSorting={true}
        allowFiltering={true}
        allowExpandAll={true}
        height={440}
        showBorders={true}
        dataSource={dataSource}>
        <FieldChooser enabled={false} />
      </PivotGrid>

      <div className="options">
        <div className="caption">Options</div>
        <div className="option">
            <CheckBox
              value={isConditional}
              text="Toggle Conditional Summary Calculation"
              onValueChanged={onValueChanged} />
        </div>
      </div>
    </div>
  );
}

export default App;

function citySelector(data) {
  return data.city + ' (' + data.country + ')';
}

// Angular/src/app/orig_app.component.ts
import { Component, ViewChild } from '@angular/core';
import { Service, Sale } from './app.service';
import { DxPivotGridComponent } from "devextreme-angular";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [Service]
})
export class AppComponent {
    @ViewChild(DxPivotGridComponent, {static: false}) pivotGrid: DxPivotGridComponent;
    sales: Sale[];
    dataSource: any;
    isConditional: boolean = true;

    constructor(service: Service) {
      let tempSales: any = service.getSales();
      
      tempSales.forEach((sale, index) => {
        sale.isApproved = index % 2 !== 0;
      });

      this.sales = tempSales;

      this.dataSource = {
          fields: [{
              caption: 'Region',
              width: 120,
              dataField: 'region',
              area: 'row',
              expanded: true
          }, {
              caption: 'City',
              dataField: 'city',
              width: 150,
              area: 'row',
              selector: this.citySelector
          }, {
              dataField: 'date',
              dataType: 'date',
              area: 'column',
              expanded: true
          }, {
              caption: 'Sales',
              dataType: 'number',
              summaryType: 'custom',
              format: 'currency',
              area: 'data',
              calculateCustomSummary: this.calculateCustomSummary
          },
          {
              caption: "Approved",
              dataField: "isApproved",
              summaryType: "sum",
              area: "data"
          }],
          store: this.sales
      }

  }

  calculateCustomSummary = (options) => {
    switch (options.summaryProcess) {
        case "start":
            options.totalValue = { conditionalVal: 0, rawVal: 0, count: 0 };
            break;
        case "calculate":
            options.totalValue.count += 1;
            options.totalValue.rawVal += options.value.amount;
            if (options.value.isApproved) {
                options.totalValue.conditionalVal += options.value.amount;
            }
            break;
        case "finalize":
            if (options.totalValue.count === 1 || !this.isConditional) {
                // If not conditional, this block will always be run
                options.totalValue = options.totalValue.rawVal;
            } else {
                options.totalValue = options.totalValue.conditionalVal;
            }
    }
}

  onValueChanged(data) {
    let ds = this.pivotGrid.instance.getDataSource()
    ds.reload()
  }

  citySelector(data) {
      return data.city + ' (' + data.country + ')';
  }
}

<div class="long-title"><h3>Sales Amount by Region</h3></div>
<dx-pivot-grid id="sales"
  [allowSortingBySummary]="true"
  [allowSorting]="true"
  [allowFiltering]="true"
  [allowExpandAll]="true"
  [height]="440"
  [showBorders]="true"
  [dataSource]="dataSource">
  <dxo-field-chooser [enabled]="false"></dxo-field-chooser>
</dx-pivot-grid>

<div class="options">
  <div class="caption">Options</div>
  <div class="option">
      <dx-check-box 
        [(value)]="isConditional"
        text="Toggle Conditional Summary Calculation"
        (onValueChanged)="onValueChanged($event)">
      </dx-check-box>
  </div>
</div>
